? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "BTCUSD", "target": "daily"}'
: headers: '{"X-CoinAPI-Key" : "88E64267-36B2-49FB-92A4-31E636CC1729"}'
  history: null
  hook: "def postRequestHook(response: 'requests.Response'):\r\n    '''{'time': '2023-05-27T15:42:21.0000000Z',\
    \ \r\n        'asset_id_base': 'BTC', \r\n        'asset_id_quote': 'USD', \r\n\
    \        'rate': 26679.519881731812}\r\n    '''\r\n    if response.status_code\
    \ == 200 and response.text != '':\r\n        return response.json().get('rate')\r\
    \n    return None"
  payload: null
  uri: https://rest.coinapi.io/v1/exchangerate/BTC/USD
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "WeatherBerlin", "target": "current_weather.temperature"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"current_weather\", {}).get(\"\
    temperature\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&current_weather=true
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbaseADA-USD", "target": "data.rates.ADA"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'):\r\n    if response.text\
    \ != '':\r\n        x = float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"ADA\", None))\r\n        if isinstance(x, float) and x > 0:\r\n  \
    \          return 1/x\r\n    return None"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=USD
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbaseALGO-USD", "target": "data.rates.ALGO"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'):\r\n    if response.text\
    \ != '':\r\n        x = float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"ALGO\", None))\r\n        if isinstance(x, float) and x > 0:\r\n \
    \           return 1/x\r\n    return None"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=USD
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbasePricesAAVE", "target": "data.rates.USD"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"USD\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=AAVE
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbasePricesADA", "target": "data.rates.USD"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"USD\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=ADA
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbasePricesALGO", "target": "data.rates.USD"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"USD\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=ALGO
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbasePricesBTC", "target": "data.rates.USD"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"USD\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=BTC
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbasePricesDOGE", "target": "data.rates.USD"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"USD\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=DOGE
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbasePricesETH", "target": "data.rates.USD"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"USD\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=ETH
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbasePricesGALA", "target": "data.rates.USD"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"USD\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=GALA
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbasePricesHBAR", "target": "data.rates.USD"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"USD\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=HBAR
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbasePricesPOLY", "target": "data.rates.USD"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"USD\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=POLY
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbasePricesUSD", "target": "data.rates.BTC"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"BTC\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=USD
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbasePricesUSD", "target": "data.rates.USD"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"USD\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=BTC
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "coinbasePricesXMR", "target": "data.rates.USD"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"USD\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=XMR
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "something", "target": ""}'
: headers: null
  history: null
  hook: null
  payload: null
  uri: http://something.com
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "something", "target": "test"}'
: headers: null
  history: null
  hook: null
  payload: null
  uri: http://something.com
? '{"source": "satori", "author": "021bd7999774a59b6d0e40d650c2ed24a49a54bdb0b46c922fd13afe8a4f3e4aeb",
  "stream": "test", "target": "test"}'
: headers: null
  history: null
  hook: null
  payload: null
  uri: http://something.com
? '{"source": "satori", "author": "039d1557e0d9f88034cc51c4806ee548c663ae9ba2baad68d3f66d5dd9e16bde40",
  "stream": "coinbaseADA-USD", "target": "data.rates.ADA"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"ADA\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=USD
? '{"source": "satori", "author": "039d1557e0d9f88034cc51c4806ee548c663ae9ba2baad68d3f66d5dd9e16bde40",
  "stream": "coinbaseADA-USD-10Min", "target": "data.rates.ADA"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \r\n    '''\r\n    called\
    \ and given the response each time\r\n    the endpoint for this data stream is\
    \ hit.\r\n    returns the value of the observaiton \r\n    as a string, integer\
    \ or double.\r\n    if empty string is returned the observation\r\n    is not\
    \ relayed to the network.\r\n    '''                    \r\n    if response.text\
    \ != '':\r\n        return float(response.json().get(\"data\", {}).get(\"rates\"\
    , {}).get(\"ADA\", None))\r\n    return None\r\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=USD
? '{"source": "satori", "author": "039d1557e0d9f88034cc51c4806ee548c663ae9ba2baad68d3f66d5dd9e16bde40",
  "stream": "coinbaseUSD-1INC", "target": "data.rates.1INCH"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \n    '''\n    called\
    \ and given the response each time\n    the endpoint for this data stream is hit.\n\
    \    returns the value of the observaiton \n    as a string, integer or double.\n\
    \    if empty string is returned the observation\n    is not relayed to the network.\n\
    \    '''                    \n    if response.text != '':\n        return float(response.json().get(\"\
    data\", {}).get(\"rates\", {}).get(\"1INCH\", None))\n    return None\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=USD
? '{"source": "satori", "author": "039d1557e0d9f88034cc51c4806ee548c663ae9ba2baad68d3f66d5dd9e16bde40",
  "stream": "coinbaseUSD-1INCH", "target": "data.rates.1INCH"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \n    '''\n    called\
    \ and given the response each time\n    the endpoint for this data stream is hit.\n\
    \    returns the value of the observaiton \n    as a string, integer or double.\n\
    \    if empty string is returned the observation\n    is not relayed to the network.\n\
    \    '''                    \n    if response.text != '':\n        return float(response.json().get(\"\
    data\", {}).get(\"rates\", {}).get(\"1INCH\", None))\n    return None\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=USD
? '{"source": "satori", "author": "039d1557e0d9f88034cc51c4806ee548c663ae9ba2baad68d3f66d5dd9e16bde40",
  "stream": "coinbaseUSD-AAVE", "target": "data.rates.AAVE"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \n    '''\n    called\
    \ and given the response each time\n    the endpoint for this data stream is hit.\n\
    \    returns the value of the observaiton \n    as a string, integer or double.\n\
    \    if empty string is returned the observation\n    is not relayed to the network.\n\
    \    '''                    \n    if response.text != '':\n        return float(response.json().get(\"\
    data\", {}).get(\"rates\", {}).get(\"AAVE\", None))\n    return None\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=USD
? '{"source": "satori", "author": "039d1557e0d9f88034cc51c4806ee548c663ae9ba2baad68d3f66d5dd9e16bde40",
  "stream": "coinbaseUSD-ABT", "target": "data.rates.ABT"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \n    '''\n    called\
    \ and given the response each time\n    the endpoint for this data stream is hit.\n\
    \    returns the value of the observaiton \n    as a string, integer or double.\n\
    \    if empty string is returned the observation\n    is not relayed to the network.\n\
    \    '''                    \n    if response.text != '':\n        return float(response.json().get(\"\
    data\", {}).get(\"rates\", {}).get(\"ABT\", None))\n    return None\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=USD
? '{"source": "satori", "author": "039d1557e0d9f88034cc51c4806ee548c663ae9ba2baad68d3f66d5dd9e16bde40",
  "stream": "coinbaseUSD-BCH", "target": "data.rates.BCH"}'
: headers: null
  history: null
  hook: "def postRequestHook(response: 'requests.Response'): \n    '''\n    called\
    \ and given the response each time\n    the endpoint for this data stream is hit.\n\
    \    returns the value of the observaiton \n    as a string, integer or double.\n\
    \    if empty string is returned the observation\n    is not relayed to the network.\n\
    \    '''                    \n    if response.text != '':\n        return float(response.json().get(\"\
    data\", {}).get(\"rates\", {}).get(\"BCH\", None))\n    return None\n"
  payload: null
  uri: https://api.coinbase.com/v2/exchange-rates?currency=USD
